In [86]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/nkjait/imdb-data-for-sentiment-analysisnaive-bayes/IMDB Dataset.csv

In [87]:
df=pd.read_csv('/kaggle/input/datasets/nkjait/imdb-data-for-sentiment-analysisnaive-bayes/IMDB Dataset.csv')

In [88]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [89]:
#One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [90]:
df=df.sample(10000)

In [91]:
df.shape

(10000, 2)

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 29193 to 17195
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [93]:
df['sentiment'].replace({'positive':1,"negative":0},inplace=True)

/tmp/ipykernel_58/2918837897.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive':1,"negative":0},inplace=True)
/tmp/ipykernel_58/2918837897.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive':1,"negative":0},inplace=True)

In [94]:
df

                                                  review  sentiment
29193  "Shivering Shakespeare" could be considered th...          1
2075   I think it's two years ago since I have seen t...          0
8629   This is a pretty strange movie. It does comes ...          1
29779  From the opening shot of the meteor falling to...          0
31737  I absolutely could not believe the levels of i...          0
...                                                  ...        ...
37808  I think the majority of the people seem not th...          1
5239   I've never been a huge fan of Mormon films. Be...          0
48604  While I can't say whether or not Larry Hama ev...          1
28492  Emilio Miraglio's "The Red Queen Kills Seven T...          1
17195  Just saw this movie, and what a waste of time....          0

[10000 rows x 2 columns]

In [95]:
import re
clean=re.compile('<.*?>')
re.sub(clean,'',df.iloc[2].review)

"This is a pretty strange movie. It does comes across as an exploitation film with over-the-top violence and unrealistic situations, but unusual for being constructed around rural characters at war with each other, as opposed to an invading 'other'.The movie is an excessive stereotype of Vietnam veterans, in a long line of films that portrayed the vets of that war as dangerous psycopaths. Kris Kristofferson's last line is 'I ain't lost a war yet', as he meets his demise after wreaking a long trail of murder and destruction, including the town's chief of police and his brother's girlfriend in a particularly chilling scene. However, Kristofferson is a good enough actor, and charismatic enough, to carry this villain with a surprising depth. Vincent is clearly the golden boy, but with enough intensity layered over his clean cut goodness. The movie bears some plot resemblance to Winchester 73 where Jimmy Stewart tries to tolerate a criminal brother until being forced to act against him.The movie has b-movie grade action, though the presence of Kristofferson, Vincent, a gorgeous Victoria Principal and Bernadette Peters give it an A-grade lineup.I give it a 7 for being a long lost view into an American psyche of post-Vietnam/pre-Reagan introspection, paranoia, and confusion, and a movie industry that was willing to address such topics at that time.Seen on the THIS channel, a great network that keeps playing lots of old movies of the 70s through 90s, regardless of political bent."

In [96]:
def clean_html(text):
    clean=re.compile('<.*?>')
    return re.sub(clean,"",text)

In [97]:
df['review']=df['review'].apply(clean_html)

In [98]:
#converting into lower case
def convert_lower(text):
    return text.lower()

In [99]:
df['review']=df['review'].apply(convert_lower)

In [100]:
def remove_special(text):
    x=''
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+' '
    return x

In [101]:
df['review']=df['review'].apply(remove_special)

In [102]:
df['review'].shape

(10000,)

In [103]:
#remove the stop words
import nltk

In [104]:
from nltk.corpus import stopwords

In [105]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [106]:
def remove_stopwords(text):
    x=[]
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)

    y=x[:]
    x.clear()
    return y

In [ ]:
import time
start=time.time()
print('start :',start)

df['review']=df['review'].apply(remove_stopwords)


end=time.time()
print('take time:',end-start)

start : 1782322253.689801

In [ ]:
df['review']

In [ ]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
y=[]
def stem_word(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [ ]:
df['review']=df['review'].apply(stem_word)

In [ ]:
df['review']

In [ ]:
def join_back(list_input):
    return ' '.join(list_input)

In [ ]:
df['review']=df['review'].apply(join_back)

In [ ]:
df['review']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(max_features=1000)
x=cv.fit_transform(df['review']).toarray()

In [ ]:
x.shape

In [ ]:
y=df.iloc[:,-1]

In [ ]:
y.shape

In [ ]:
#train set
#test set
#x,y
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
y_train.shape

In [ ]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [ ]:
Gnb=GaussianNB()
mnb=MultinomialNB()
Bnb=BernoulliNB()

In [ ]:
Gnb.fit(x_train,y_train)
g_y_pred=Gnb.predict(x_test)

In [ ]:
Bnb.fit(x_train,y_train)
b_y_pred=Bnb.predict(x_test)

In [ ]:
mnb.fit(x_train,y_train)
m_y_pred=mnb.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score

#### print(f'gnb accuracy:{accuracy_score(y_test,g_y_pred)}')
print(f'mnb accuracy:{accuracy_score(y_test,m_y_pred)}')
print(f'bnb accuracy:{accuracy_score(y_test,b_y_pred)}')

In [ ]:
Bnb.predict(())